// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "backend/libs/db/prisma/schema.prisma",
  migrations: {
    path: "backend/libs/db/prisma/migrations",
  },
  datasource: {
    // For generate command, DATABASE_URL is not required, so we provide a placeholder
    // For migrate/push commands, DATABASE_URL must be set in environment
    url: process.env.DATABASE_URL || "postgresql://placeholder:placeholder@localhost:5432/placeholder",
  },
});
